### ISSUE TITLE
Explicite connection to mongo replicaset

### ISSUE THREAD

**Issue by vgresselin-pro** [gisaia/ARLAS-subscriptions#181]
The arlas-subscription-manager connects to mongodb through configuration of a single host name. To connect explicitly to a mongodb replicaset it should be possible (but optinal) to provide a replicaset name as a HELM configuration which would be used by the mongo client.

**Comment by alainbodiguel** [comment]
It will be configured via the MONGO_HOST env variable. 

Before:
MONGO_HOST=mongodb
MONGO_PORT=27017

After:
MONGO_HOST=mongo1:271017,mongo2:27017,mongo3:27017
(MONGO_PORT is no longer used)

**Comment by alainbodiguel** [comment]
The fix is available in version 19.7.8
