### ISSUE TITLE
[0.4.0-4][manager] Update a subscription (internal mode)

### ISSUE THREAD

**Issue by alainbodiguel** [gisaia/ARLAS-subscriptions#19]
- [ ] Implement REST endpoint PUT /admin/subscriptions/{subId} (update in both database and index, an error in one must prevent the other one to be updated)
- [ ] a request to the admin endpoints with identity!={admin} should return an error 403
- [ ] TI

**Comment by laurent-thiebaud-gisaia** [comment]
@alainbodiguel should we also use a DELETE parameter, in order to update a deleted or not subscripton? Or should we limit the update to no-deleted subscriptions?

**Comment by laurent-thiebaud-gisaia** [comment]
I propose to return a 404 in this case, also for usual users (the subscription to update is not found, as already deleted)

**Comment by alainbodiguel** [comment]
Sounds good to me.
