### ISSUE TITLE
[0.4.0-5][manager] Delete a subscription (internal mode)

### ISSUE THREAD

**Issue by alainbodiguel** [gisaia/ARLAS-subscriptions#20]
- [ ] Implement REST endpoint DELETE /admin/subscriptions/{subId} (delete in both database and index, an error in one must prevent the other one to be updated)
- [ ] a request to the admin endpoints with identity!={admin} should return an error 403
- [ ] TI

**Comment by laurent-thiebaud-gisaia** [comment]
@alainbodiguel what to do if the user tries to delete a deleted subcriptions?

**Comment by alainbodiguel** [comment]
Silently do it again (will not change the status of the sub in the end as the attribute 'deleted' will remain 'true').
