### ISSUE TITLE
Manager : create subscription index from json schema

### ISSUE THREAD

**Issue by mbarbet** [gisaia/ARLAS-subscriptions#64]
Currently :
The user must create the subscription index before launch the manager. The trigger part should be compliant with the geo and search request, it is the responsability of the user.

Improvement:
Use a template for the mapping based on:
`{
  "_source": {
    "enabled": true
  },
  "dynamic": false,
  "properties": {
    "id": {
      "type": "keyword"
    },
    "created_at": {
      "type": "date"
    },
    "modified_at": {
      "type": "date"
    },
    "created_by_admin": {
      "type": "boolean"
    },
    "deleted": {
      "type": "boolean"
    },
    "created_by": {
      "type": "text"
    },
    "active": {
      "type": "boolean"
    },
    "starts_at": {
      "type": "date",
      "format": "epoch_second"
    },
    "expires_at": {
      "type": "date",
      "format": "epoch_second"
    },
    "title": {
      "type": "text"
    },
    "subscription": {
      "properties": {
        "trigger": {
          "properties": {
            "geometry": {
              "type": "geo_shape"
            },
            "event": {
              "type": "keyword"
            },
            "job": {
              "type": "keyword"
            }
          }
        },
        "callback": {
          "type": "text"
        },
        "hits": {
          "properties": {
            "filter": {
              "type": "text"
            },
            "projection": {
              "type": "text"
            }
          }
        }
      }
    },
    "user_metadatas": {
      "type": "object"
    },
    "geometry": {
      "type": "geo_shape"
    },
    "centroid": {
      "type": "geo_point"
    }
  }
}`

and replace the trigger part by  the field define  in the json schema.
-- All array as keywords
-- All string as keywords
-- All number as double
-- All object as object (this fiel will be not queryable)

**Comment by alainbodiguel** [comment]
Not planned for now.
